#skip = True
import subprocess, sys, os, VolumeComparison as vc
import random

title = "Cage match. Can LLMs design interlocking parts for 3D printing?"

prompt = """

I would like you to generate a cage of internal size 350 x 350 x 700 mm. 

The cage should feature an all-around grid of 10mm thick bars, each with a square cross section. No thinner, no thicker.

The gap between bars should be between 5cm and 10cm, and uniform all over the model.

The cage needs to be split into parts that can be 3D printed on a 3D printer, with a build area
of 400x400x50mm.

The cage assembly should be held together by 4 x M6 threaded rods threaded through the middle
of the 4 vertical corner bars. You do not need to carve a female thread or nut slots into your parts,
but should ensure that a rod fits with adequete clearence into every hole. Use no additional connectors. Do not include
a door or lid.

Generate all parts that are needed for this project. They should be:
- ready to slice
- print without supports.
- orientated such that they fit within the build volume
- sitting on z=0 plane.
- not going to fall over during printing.
- valid shapes - watertight, closed solids with no self intersections.
- As few parts as possible.
- Use as little build volume of the 3D printer as possible.

For each part file, you may provide an STL file, or OpenSCAD file that generates it, or a python script that 
generates either the OpenSCAD or the STL. Provide all parts in one go into the supplied output structure.

For each part, include a rigid transform matrix (4x4 row major) that shows where the part sits in 3D space when assembled, in
your assembled 3D space, the cage sits on the z=0 plane and centred in x & y around 0,0.
Take care to get this projection right as it will be used to test whether the parts fit together correctly. 

"""

structure = {
  "type": "object",
  "properties": {
    "reasoning": {
      "type": "string"
    },
    "parts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "fileContents": {
            "type":
            "string",
            "description":
            "Either a raw STL file (first word is 'solid'), "
            "a valid OpenSCAD file that generates the STL file."
            "a Python script that when run, outputs the STL file to stdout."
          },
          "fileType": {
            "type": "string",
            "enum": ["STL", "OpenSCAD", "Python Generating OpenSCAD", "Python Generating STL"],
            "description": "The type of file generated by the AI"
          },
          "transform": {
            "type": "array",
            "items": {
              "type":
              "number",
              "description":
              "The 4x4 transform matrix for this part. Must be a rigid transform (no scale or skew)."
            }
          }
        },
        "required": ["fileContents", "transform", "fileType"],
        "additionalProperties": False,
        "propertyOrdering": ["fileContents", "transform", "fileType"]
      }
    }
  },
  "required": ["parts", "reasoning"],
  "propertyOrdering": ["reasoning", "parts"],
  "additionalProperties": False
}

extraGradeAnswerRuns = [1, 2, 3, 4, 5, 6]
earlyFail = False


def _file_content_changed(filepath: str, new_content: str) -> bool:
  """Check if file doesn't exist or has different content than new_content."""
  if not os.path.exists(filepath):
    return True
  try:
    with open(filepath, "r", encoding="utf-8") as f:
      return f.read() != new_content
  except Exception:
    return True


def _write_if_changed(filepath: str, content: str) -> bool:
  """Write content to file only if it changed. Returns True if file was written."""
  if _file_content_changed(filepath, content):
    with open(filepath, "w", encoding="utf-8") as f:
      f.write(content)
    return True
  return False


def gradeAnswer(answer: dict, subPass: int, aiEngineName: str):
  global earlyFail
  score = 0
  bugs = ""
  import scad_format

  if "parts" not in answer:
    return 0, "Answer did not contain a 'parts' key."

  if len(answer["parts"]) > 10:
    return 0, "Answer contained too many parts. 10 max"

  if subPass == 0:
    any_posed_changed = False
    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      needs_regenerate = False

      # Determine source file path and check if content changed
      if part["fileType"].lower() == "stl":
        source_path = "results/" + partName + ".stl"
        needs_regenerate = _write_if_changed(source_path, part["fileContents"])

      elif part["fileType"].lower() == "openscad":
        source_path = "results/" + partName + ".scad"
        formatted = part["fileContents"]
        formatted = scad_format.format(formatted, vc.formatConfig)
        needs_regenerate = _write_if_changed(source_path, formatted)

      elif part["fileType"].lower() == "python generating openscad":
        source_path = "results/" + partName + ".py"
        needs_regenerate = _write_if_changed(source_path, part["fileContents"])

        if needs_regenerate:
          try:
            subprocess.run(sys.executable, [partName + ".py"],
                           stdout=open("results/" + partName + ".scad", "w", encoding="utf-8"),
                           cwd="results")
          except Exception as e:
            bugs += "Python generating OpenSCAD for " + partName + " failed due to " + str(
              e) + "<br>"

          scad_format.format_file("results/" + partName + ".scad", "results/" + partName + ".scad",
                                  vc.formatConfig)

      elif part["fileType"].lower() == "python generating stl":
        source_path = "results/" + partName + ".py"
        needs_regenerate = _write_if_changed(source_path, part["fileContents"])

        if needs_regenerate:
          try:
            subprocess.run(sys.executable, ["results/" + partName + ".py"],
                           stdout=open("results/" + partName + ".stl", "w", encoding="utf-8"),
                           cwd="results")
          except Exception as e:
            bugs += "Python generating STL for " + partName + " failed due to " + str(e) + "<br>"
      else:
        bugs += "Unknown file type '" + part["fileType"] + "' for " + partName + "<br>"

      # Generate STL from OpenSCAD if needed
      if os.path.exists("results/" + partName + ".scad") and (
          needs_regenerate or not os.path.exists("results/" + partName + ".stl")):
        try:
          subprocess.run([vc.openScadPath, partName + ".scad", "-o", partName + ".stl"],
                         cwd="results")
        except Exception as e:
          bugs += "OpenSCAD failed to generate STL for " + partName + " due to " + str(e) + "<br>"

      # Generate posed STL if needed
      posed_scad_content = f"""
    multmatrix([{part["transform"][0:4]}, 
                {part["transform"][4:8]}, 
                {part["transform"][8:12]}, 
                {part["transform"][12:16]}]) import("{partName}.stl");
                        """
      posed_scad_path = "results/" + partName + "_posed.scad"
      posed_changed = _write_if_changed(posed_scad_path,
                                        scad_format.format(posed_scad_content, vc.formatConfig))

      if os.path.exists("results/" + partName + ".stl") and bugs == "" and (
          needs_regenerate or posed_changed
          or not os.path.exists("results/" + partName + "_posed.stl")):
        try:
          subprocess.run([vc.openScadPath, partName + "_posed.scad", "-o", partName + "_posed.stl"],
                         cwd="results")
        except Exception as e:
          bugs += "OpenSCAD failed to generate posed STL for " + partName + " due to " + str(
            e) + "<br>"

      if needs_regenerate or posed_changed:
        any_posed_changed = True

    # Generate fullposed assembly
    colourNames = [
      "Red", "Green", "Blue", "Yellow", "Cyan", "Magenta", "Brown", "White", "Orange", "Grey"
    ]
    fullposed_scad_content = ""
    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + str(aiEngineName)
      fullposed_scad_content += f"color(\"{colourNames[partIndex]}\") import(\"{partName}_posed.stl\");\n"

    fullposed_scad_path = "results/29_" + str(aiEngineName) + "_fullposed.scad"
    any_posed_changed |= _write_if_changed(
      fullposed_scad_path, scad_format.format(fullposed_scad_content, vc.formatConfig))

    if bugs == "" and (any_posed_changed
                       or not os.path.exists("results/29_" + str(aiEngineName) + "_fullposed.stl")):
      try:
        subprocess.run([
          vc.openScadPath, "29_" + str(aiEngineName) + "_fullposed.scad", "-o",
          "29_" + str(aiEngineName) + "_fullposed.stl"
        ],
                       cwd="results")
      except Exception as e:
        bugs += "OpenSCAD failed to generate fullposed STL for " + str(
          aiEngineName) + " due to " + str(e) + "<br>"

    # Basic validation: Correct number of parts, and non-zero sized stl files.
    if len(answer["parts"]) != 10:
      bugs += "Expected 10 parts, got " + str(len(answer["parts"])) + "<br>"

    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + str(aiEngineName)
      stlFile = "results/" + partName + ".stl"

      if not os.path.exists(stlFile):
        bugs += "Part " + str(stlFile) + " does not exist<br>"
        continue

      # check file size is not 0
      if os.path.getsize(stlFile) == 0:
        bugs += "Part " + str(stlFile) + " was empty<br>"

      volume = vc.StlVolume.calculate_stl_volume(stlFile)
      print(partName + " Volume: " + str(volume))
      if volume == 0:
        bugs += "Part " + str(partIndex) + ".stl had a volume of 0<br>"

    earlyFail = bugs != ""
    return 0 if earlyFail else 1, bugs

  if earlyFail == True:
    return 0, "Failed as prerequestite test has failed."

  if subPass == 1:
    # Does it fit in the build volume?
    score = 0
    bugs = ""
    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"

      overFlowsFromBuildVolume = vc.hit_tests(
        stlFile, ["translate([0,0,25]) cube([400,400,50], center=true)"], "difference")

      if overFlowsFromBuildVolume[0] == True:
        bugs += "Part " + str(
          partIndex) + ".stl does not fit in build volume or intersects with the floor<br>"
      else:
        score += 0.1

    return score, bugs

  if subPass == 2:
    # Does it have the correct gap between bars?
    tests4 = []
    tests10 = []

    def randomFloat(min, max):
      return random.uniform(min, max)

    for i in range(32):
      tests4.append(
        f"translate([{randomFloat(-120,120)},{randomFloat(-120,120)},0]) cube([40,40,40], center=true);"
      )
      tests10.append(
        f"translate([{randomFloat(-160,160)},{randomFloat(-160,160)},0]) cube([101,101,40], center=true);"
      )

    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"
      results4 = vc.hit_tests(stlFile, tests4)
      results10 = vc.hit_tests(stlFile, tests10)

      if all(results4):
        bugs += "Part " + str(
          partIndex
        ) + ".stl always intersected a randomly placed 40mm cube. Gap between bars should be 50mm or higher.<br>"
      if not all(results10):
        bugs += "Part " + str(
          partIndex
        ) + ".stl allowed a 101mm cube to pass through. Gap between bars should be 100mm or lower.<br>"

      if bugs == "":
        for i in range(32):
          if results4[i] == False:
            scad = "color(\"grey\") import(\"" + partName + ".stl\");\n" + tests4[i]
            scad = scad_format.format(scad, vc.formatConfig)
            vc.render_scadText_to_png(
              scad, "results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_40mm.png")
            break

      if not all(results10):
        for i in range(32):
          if results10[i] == False:
            scad = "color(\"grey\") import(\"" + partName + ".stl\");\n" + tests10[i]
            scad = scad_format.format(scad, vc.formatConfig)
            vc.render_scadText_to_png(
              scad, "results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_101mm.png")
            break

    return 1 if bugs == "" else 0, bugs

  if subPass == 3:
    # Are the transform matrices correct and the cage is about the right size?
    tests = [
      "translate([0,0,360]) cube([340,340,680], center=true);",
      "translate([0,0,370]) difference() {cube([1000,1000,1000], center=true); cube([380,380,740], center=true);}",
    ]

    results = vc.hit_tests("results/29_" + str(aiEngineName) + "_fullposed.stl", tests)

    if results[0] == True:
      return 0, "Cage is too small or invalid transform matrices - a 350x350x700 needs to fit inside without intersecting the bars."
    if results[1] == True:
      return 0, "Cage is too large or invalid transform matrices - Cage must hold 350x350x700mm with 10mm thick bars"

    return 1, ""

  if subPass == 4:
    tests = [
      "translate([-180, -180, 0]) cylinder(r=5, h=360, center=true);",
      "translate([180, -180, 0]) cylinder(r=5, h=360, center=true);",
      "translate([-180, 180, 0]) cylinder(r=5, h=360, center=true);",
      "translate([180, 180, 0]) cylinder(r=5, h=360, center=true);",
      "translate([-180, -180, 0]) cylinder(r=8, h=360, center=true);",
      "translate([180, -180, 0]) cylinder(r=8, h=360, center=true);",
      "translate([-180, 180, 0]) cylinder(r=8, h=360, center=true);",
      "translate([180, 180, 0]) cylinder(r=8, h=360, center=true);",
    ]

    results = vc.hit_tests("results/29_" + str(aiEngineName) + "_fullposed.stl", tests)

    for i in enumerate(results[0:3]):
      if i == True:
        return 0, f"Error during simulated assembly: Unable to thread a 6mm rod through the cage segments (at {tests[i]}), it intersects the cage or bars."

    for i in enumerate(results[3:]):
      if i == False:
        return 0, f"Error during simulated assembly: Unable to use a 6mm rod through the cage segments (at {tests[i]}), it has so much clearence that a nut would just slide right through."

    return 1, ""

  if subPass == 5:
    for partIndexA, partA in enumerate(answer["parts"]):
      partNameA = "29_" + str(partIndexA) + "_" + aiEngineName
      stlFileA = "results/" + partNameA + "_posed.stl"
      tests = []
      for partIndexB, partB in enumerate(answer["parts"]):
        if partIndexA >= partIndexB:
          continue

        partNameB = "29_" + str(partIndexB) + "_" + aiEngineName
        stlFileB = "results/" + partNameB + "_posed.stl"
        tests.append("difference() {import(\"" + stlFileA + "\") ; import(\"" + stlFileB + "\")}")

      results = vc.hit_tests(stlFileA, tests)
      if any(results):
        return 0, "When assembled, part " + str(partIndexA) + " intersects with part " + str(
          partIndexB)

    return 1, ""

  if subPass == 6:
    bugs = ""
    for partIndexA, partA in enumerate(answer["parts"]):
      partNameA = "29_" + str(partIndexA) + "_" + aiEngineName
      stlFileA = "results/" + partNameA + "_posed.stl"

      tests = [
        "translate([-180, -180, 400]) cylinder(r=8, h=800, center=true);",
        "translate([180, -180, 400]) cylinder(r=8, h=800, center=true);",
        "translate([-180, 180, 400]) cylinder(r=8, h=800, center=true);",
        "translate([180, 180, 400]) cylinder(r=8, h=800, center=true);",
      ]

      results = vc.hit_tests(stlFileA, tests)
      intersectionCount = sum(results)
      if intersectionCount == 0:
        bugs += "When assembled, part " + str(
          partIndexA
        ) + " is not held in place by the threaded rods, and will fall out from the build when assembled.\n"

      if intersectionCount == 1:
        bugs += "When assembled, part " + str(
            partIndexA
        ) + " is only held in place by one threaded rod, allowing" \
        " it to rotate around a rod. Since the design brief said no doors or lids," \
        " such a part should not appear in the final design."

      scad = ""
      for i in range(4):
        if results[i] == True:
          scad += f"""
color("red") intersection() {{
{tests[i].replace('r=8','r=2')}
hull() {{
  translate([0,0,-50]) import("{partNameA}_posed.stl");
  translate([0,0,50]) import("{partNameA}_posed.stl");
}} 
}}
"""
      scad += "color(\"grey\") import(\"" + partNameA + "_posed.stl\");\n"
      scad = scad_format.format(scad, vc.formatConfig)
      vc.render_scadText_to_png(
        scad, "results/29_" + str(partIndexA) + "_" + str(aiEngineName) + "_6mm.png")

    return 1 if bugs == "" else 0, bugs

  return 10000, "Nobody has gotten this far before... Need to write more parts of the test."


def resultToNiceReport(answer: dict, subPass: int, aiEngineName: str):
  if subPass == 0:
    return "Checks to see if the correct number of parts are rendered (10), and whether the STL files exist and are non-zero sized. " + \
           "Some particully clueless AIs might generate 14 files (as 700mm/50mm == 14), which gets an instant 0 for wasting 4 prints"

  if subPass == 1:
    out = "Check to see if the parts are printable - resting on the z=0 plane, watertight, and within print bounds:<br>"
    for partIndex in range(10):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"
      if os.path.exists(stlFile):
        vc._render_stl_to_png(stlFile, "results/" + partName + ".png")
        out += "<img src='" + partName + ".png' width=320/>"
    return out

  if subPass == 2:
    out = ""
    for partIndex in range(10):
      if os.path.exists("results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_40mm.png"):
        out += "<img src='29_" + str(partIndex) + "_" + str(aiEngineName) + "_40mm.png' width=320/>"
      if os.path.exists("results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_101mm.png"):
        out += "<img src='29_" + str(partIndex) + "_" + str(
          aiEngineName) + "_101mm.png' width=320/>"
    return out + """
<br>Check to see if the bars in cage segments are correctly sized and spaced. 
Can a 50mm cube pass through the bars? Does a 100mm cube get blocked?
"""

  if subPass == 3:
    out = "Check to see if the part transform matrices are correct and the cage is correctly sized."

    if os.path.exists("results/29_" + aiEngineName + "_fullposed.stl"):
      vc.render_scadText_to_png("include<29_" + aiEngineName + "_fullposed.scad>",
                                "results/29_" + aiEngineName + "_fullposed.png")

      out += "<img src='29_" + aiEngineName + "_fullposed.png' width=640/>"

    return out

  if subPass == 4:
    return "Check to see if a 6mm threaded rod can fit through the cage segments."

  if subPass == 5:
    return "Check to see if projected parts intersect each other."

  if subPass == 6:
    out = ""
    for partIndex in range(10):
      if os.path.exists("results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_6mm.png"):
        out += "<img src='29_" + str(partIndex) + "_" + str(aiEngineName) + "_6mm.png' width=320/>"
    return out + "<br>Check to see if every part is connected via the rod."


highLevelSummary = """
This is the hardest problem in here - turn a description of a large 3D model into printable 
parts that connect together without interfering.
<br><br>
Only one LLM has managed to even plan the split correctly yet.<br><br>

To be nice to the LLMs, we accept python, OpenSCAD, or STL format for the parts.<br><br>

A very suboptimal LLM might just divide the cage into 14 parts (as 700mm/50mm == 14),
which gets an instant 0 for wasting 4 prints.
<br><br>
The optimal split is 10 parts - top, bottom, and 2 segments each for the 
east, north, west and south. Each cage segment needs to make sure that the corner
bars are not double printed on adjacent segments, and each needs to make sure that the
6mm threaded rod can pass through tight enough that a nut would not slide right through.
"""

if __name__ == "__main__":
  import sys
  sys.path.append("placebo_data")
  import q29
  answer = q29.get_response(0)[0]
  gradeAnswer(answer, 0, "OpenSCAD")
  print(gradeAnswer(answer, 6, "OpenSCAD"))
  print(resultToNiceReport(answer, 6, "OpenSCAD"))
