#skip = True
import subprocess, sys, os, VolumeComparison as vc

title = "Cage match. Can LLMs design interlocking parts for 3D printing?"

prompt = """

I would like you to generate a cage of internal size 350 x 350 x 700 mm. 

The cage should feature an all-around grid of 10mm thick bars, each with a square cross section. No thinner, no thicker.

The gap between bars should be between 5cm and 10cm, and uniform all over the model.

The cage needs to be split into parts that can be 3D printed on a 3D printer, with a build area
of 400x400x50mm.

The cage assembly should be held together by 4 x M6 threaded rods threaded through the middle
of the 4 vertical corner bars. You do not need to carve a female thread or nut slots into your parts,
but should ensure that a rod fits with adequete clearence into every hole. Use no additional connectors.

Generate all parts that are needed for this project. They should be:
- ready to slice
- print without supports.
- orientated such that they fit within the build volume
- sitting on z=0 plane.
- not going to fall over during printing.
- valid shapes - watertight, closed solids with no self intersections.
- As few parts as possible.

For each part file, you may provide an STL file, or OpenSCAD file that generates it, or a python script that 
generates either the OpenSCAD or the STL. Provide all parts in one go into the supplied output structure.

For each part, include a rigid transform matrix that shows where the part sits in 3D space when assembled, in
your assembled 3D space, the cage sits on the z=0 plane and centred in x & y around 0,0.
Take care to get this projection right as it will be used to test whether the parts fit together correctly. 

"""

structure = {
    "type": "object",
    "properties": {
        "reasoning": {
            "type": "string"
        },
        "parts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "fileContents": {
                        "type":
                        "string",
                        "description":
                        "Either a raw STL file (first word is 'solid'), "
                        "a valid OpenSCAD file that generates the STL file."
                        "a Python script that when run, outputs the STL file to stdout."
                    },
                    "fileType": {
                        "type":
                        "string",
                        "enum": [
                            "STL", "OpenSCAD", "Python Generating OpenSCAD",
                            "Python Generating STL"
                        ],
                        "description":
                        "The type of file generated by the AI"
                    },
                    "transform": {
                        "type": "array",
                        "items": {
                            "type":
                            "number",
                            "description":
                            "The 4x4 transform matrix for this part. Must be a rigid transform (no scale or skew)."
                        }
                    }
                },
                "required": ["fileContents", "transform", "fileType"],
                "additionalProperties": False,
                "propertyOrdering": ["fileContents", "transform", "fileType"]
            }
        }
    },
    "required": ["parts", "reasoning"],
    "propertyOrdering": ["reasoning", "parts"],
    "additionalProperties": False
}

extraGradeAnswerRuns = [1, 2, 3, 4, 5, 6]
earlyFail = False


def gradeAnswer(answer: dict, subPass: int, aiEngineName: str):
    global earlyFail
    score = 0
    bugs = ""

    if "parts" not in answer:
        return 0, "Answer did not contain a 'parts' key."

    for partIndex, part in enumerate(answer["parts"]):
        partName = "29_" + str(partIndex)

        if not os.path.exists("results/" + partName + ".stl"):
            if part["fileType"] == "STL":
                open("results/" + partName + ".stl", "w",
                     encoding="utf-8").write(part["fileContents"])

            elif part["fileType"] == "OpenSCAD":
                open("results/" + partName + ".scad", "w",
                     encoding="utf-8").write(part["fileContents"])

            elif part["fileType"] == "Python Generating OpenSCAD":
                open("results/" + partName + ".py", "w",
                     encoding="utf-8").write(part["fileContents"])

                try:
                    subprocess.run(sys.executable, [partName + ".py"],
                                   stdout=open("results/" + partName + ".scad",
                                               "w",
                                               encoding="utf-8"),
                                   cwd="results")
                except Exception as e:
                    bugs += "Python generating OpenSCAD for " + partName + " failed due to " + str(
                        e) + "<br>"

            elif part["fileType"] == "Python Generating STL":
                open("results/" + partName + ".py",
                     "w").write(part["fileContents"])

                try:
                    subprocess.run(sys.executable,
                                   ["results/" + partName + ".py"],
                                   stdout=open("results/" + partName + ".stl",
                                               "w",
                                               encoding="utf-8"),
                                   cwd="results")
                except Exception as e:
                    bugs += "Python generating STL for " + partName + " failed due to " + str(
                        e) + "<br>"

            if os.path.exists("results/" + partName + ".scad"):
                try:
                    subprocess.run([
                        vc.openScadPath, partName + ".scad", "-o",
                        partName + ".stl"
                    ],
                                   cwd="results")
                except Exception as e:
                    bugs += "OpenSCAD failed to generate STL for " + partName + " due to " + str(
                        e) + "<br>"

    if subPass == 0:
        # Basic crap. Correct number of parts, and non-zero sized stl files.
        score = 0
        bugs = ""
        if len(answer["parts"]) != 10:
            bugs += "Expected 10 parts, got " + str(len(
                answer["parts"])) + "<br>"
        else:
            score += 0.5

        for partIndex, part in enumerate(answer["parts"]):
            partName = "29_" + str(partIndex)

            # check file size is not 0
            if os.path.getsize("results/" + partName + ".stl") == 0:
                bugs += "Part " + str(partIndex) + ".stl was empty<br>"
            else:
                score += 0.05

        earlyFail = score < 0.9
        return score, bugs

    if earlyFail == True:
        return 0, "Failed as prerequestite test has failed."

    return 100, "Nobody has gotten this far before... Need to write more parts of the test."


def resultToNiceReport(answer: dict, subPass: int, aiEngineName: str):
    if subPass == 0:
        return "Checks to see if the correct number of parts are rendered (10), and whether the STL files exist and are non-zero sized. " + \
               "Some particully clueless AIs might generate 14 files (as 700mm/50mm == 14), which gets an instant 0 for wasting 4 prints"

    if subPass == 1:
        return "Check to see if the parts are printable - resting on the z=0 plane, watertight, and within print bounds"

    if subPass == 2:
        return "Check to see if the bars in cage segments are correctly sized and spaced."

    if subPass == 3:
        return "Check to see if the part transform matrices are correct and the cage is correctly sized."

    if subPass == 4:
        return "Check to see if a 6mm threaded rod can fit through the cage segments."

    if subPass == 5:
        return "Check to see if projected parts intersect each other."

    if subPass == 6:
        return "Check to see if every part is connected via the rod."


highLevelSummary = """
This is the hardest problem in here - turn a large 3D model into printable 
parts that connect together without interfering.
<br><br>
No LLM has managed to even plan the split correctly yet, so this questions
grading is still not yet implemented because every taker gets basically an early
exit check at the "are the parts not zero bytes"? checks. If you see out of 
bounds scores like 100/1, then you've advanced to the point where I need to implement
the grading.

A very suboptimal LLM might just divide the cage into 14 parts (as 700mm/50mm == 14),
which gets an instant 0 for wasting 4 prints.
<br><br>
The optimal split is 10 parts - top, bottom, and 2 segments each for the 
east, north, west and south. Each cage segment needs to make sure that the corner
bars are not double printed on adjacent segments.
"""
